/**
 * @fileoverview App type definitions for Radiant Finance.
 *
 * Entity types (database row shapes) are auto-generated by stellar-drive
 * from the schema definition in `src/lib/schema.ts`. This file re-exports
 * them and adds two layers of app-specific types:
 *
 * 1. **Type narrowings** — Refine generated `string` fields to precise union
 *    types (e.g., `AccountType = 'depository' | 'credit'`). These are used
 *    in UI components and business logic where type safety matters beyond
 *    what the schema generator can infer.
 *
 * 2. **Composite types** — Rich interfaces that combine data from multiple
 *    tables or include computed fields (e.g., `BudgetWithSpend` joins budget
 *    data with current-period spend calculations).
 */

// Re-export stellar-drive utility types
export type { SyncStatus, AuthMode, OfflineCredentials } from 'stellar-drive/types';

// Re-export all generated entity types
export type {
  TellerEnrollment,
  Account,
  Transaction,
  Category,
  Budget,
  BudgetPeriod,
  RecurringTransaction,
  NetWorthSnapshot,
  SpendingInsight,
  UserSettings,
  CategoryRule
} from './types.generated';

/* ═══════════════════════════════════════════════════════════════════════════
   TYPE NARROWINGS — Refine generated `string` types to precise unions
   ═══════════════════════════════════════════════════════════════════════════ */

/**
 * Top-level account classification from the Teller API.
 *
 * - `'depository'` — Bank accounts (checking, savings, money market, etc.)
 * - `'credit'` — Credit card accounts
 */
export type AccountType = 'depository' | 'credit';

/**
 * Detailed account subtype from the Teller API.
 *
 * Depository subtypes: checking, savings, money_market, certificate_of_deposit, treasury, sweep.
 * Credit subtypes: credit_card.
 *
 * @example
 * ```ts
 * const isCreditCard = (subtype: AccountSubtype) => subtype === 'credit_card';
 * ```
 */
export type AccountSubtype =
  | 'checking'
  | 'savings'
  | 'money_market'
  | 'certificate_of_deposit'
  | 'treasury'
  | 'sweep'
  | 'credit_card';

/**
 * Whether a financial account is currently active or has been closed.
 *
 * - `'open'` — Account is active and receiving transactions
 * - `'closed'` — Account has been closed at the institution
 */
export type AccountStatus = 'open' | 'closed';

/**
 * Settlement status of a transaction from the Teller API.
 *
 * - `'posted'` — Transaction has been finalized by the institution
 * - `'pending'` — Transaction is authorized but not yet settled
 */
export type TransactionStatus = 'posted' | 'pending';

/**
 * Teller API's built-in transaction category labels.
 *
 * These are assigned by Teller's classification engine and stored in
 * `Transaction.teller_category`. They can be mapped to user-defined
 * categories via `Category.teller_categories` JSON field.
 */
export type TellerCategory =
  | 'accommodation'
  | 'advertising'
  | 'bar'
  | 'charity'
  | 'clothing'
  | 'dining'
  | 'education'
  | 'electronics'
  | 'entertainment'
  | 'fuel'
  | 'general'
  | 'groceries'
  | 'health'
  | 'home'
  | 'income'
  | 'insurance'
  | 'investment'
  | 'loan'
  | 'office'
  | 'phone'
  | 'service'
  | 'shopping'
  | 'software'
  | 'sport'
  | 'tax'
  | 'transport'
  | 'transportation'
  | 'utilities';

/**
 * Classification for user-defined categories.
 *
 * - `'expense'` — Money going out (groceries, rent, subscriptions)
 * - `'income'` — Money coming in (salary, freelance, interest)
 * - `'transfer'` — Movement between accounts (not counted as income or expense)
 */
export type CategoryType = 'expense' | 'income' | 'transfer';

/**
 * Time period over which a budget is measured.
 *
 * - `'monthly'` — Reset each calendar month (most common)
 * - `'weekly'` — Reset each week
 * - `'yearly'` — Reset each calendar year
 */
export type BudgetPeriodType = 'monthly' | 'weekly' | 'yearly';

/**
 * How often a recurring transaction repeats.
 *
 * Used for cash-flow forecasting and upcoming bill reminders.
 */
export type RecurringFrequency = 'weekly' | 'biweekly' | 'monthly' | 'quarterly' | 'yearly';

/**
 * Connection health of a Teller enrollment.
 *
 * - `'connected'` — Actively syncing data from the institution
 * - `'disconnected'` — User manually disconnected or session expired
 * - `'error'` — Sync failed; see `TellerEnrollment.error_message` for details
 */
export type EnrollmentStatus = 'connected' | 'disconnected' | 'error';

/**
 * Which transaction field a category rule inspects for pattern matching.
 *
 * - `'description'` — The transaction's description text
 * - `'counterparty_name'` — The merchant or payee name
 * - `'amount'` — The transaction amount (for amount-based rules)
 */
export type MatchField = 'description' | 'counterparty_name' | 'amount';

/**
 * How a category rule compares the field value against its pattern.
 *
 * - `'contains'` — Field includes the match value as a substring
 * - `'exact'` — Field equals the match value exactly
 * - `'starts_with'` — Field begins with the match value
 * - `'regex'` — Field is tested against the match value as a regular expression
 */
export type MatchType = 'contains' | 'exact' | 'starts_with' | 'regex';

/**
 * Types of pre-computed spending analytics stored in `spending_insights`.
 *
 * - `'spending_by_category'` — Total spend broken down by category
 * - `'income_vs_expense'` — Side-by-side income and expense totals
 * - `'top_merchants'` — Ranked list of merchants by transaction volume
 * - `'daily_spending'` — Day-by-day spending amounts for sparklines
 * - `'monthly_trend'` — Month-over-month spending trend data
 */
export type InsightType =
  | 'spending_by_category'
  | 'income_vs_expense'
  | 'top_merchants'
  | 'daily_spending'
  | 'monthly_trend';

/**
 * Teller API environment selector.
 *
 * - `'sandbox'` — Fake data for development/testing
 * - `'development'` — Real bank connections with limited features
 * - `'production'` — Full production access (requires Teller approval)
 */
export type TellerEnvironment = 'sandbox' | 'development' | 'production';

/* ═══════════════════════════════════════════════════════════════════════════
   COMPOSITE TYPES — Rich types with joined/computed data
   ═══════════════════════════════════════════════════════════════════════════ */

/**
 * A transaction row enriched with its resolved category display metadata.
 *
 * Used in transaction list views where each row shows the category icon and
 * color alongside the transaction details, avoiding repeated category lookups.
 */
export interface TransactionWithCategory {
  /** UUID primary key of the transaction. */
  id: string;
  /** Foreign key to the parent account. */
  account_id: string;
  /** Transaction amount as a decimal string (negative for debits). */
  amount: string;
  /** Transaction date in YYYY-MM-DD format. */
  date: string;
  /** Raw transaction description from the institution. */
  description: string;
  /** Merchant or payee name, if identified by Teller. */
  counterparty_name: string | null;
  /** Whether the transaction is posted or pending. */
  status: TransactionStatus;
  /** Teller-assigned transaction type (e.g., "card_payment", "ach"), if available. */
  type: string | null;
  /** Display name of the assigned category, or `null` if uncategorized. */
  category_name: string | null;
  /** Emoji/icon of the assigned category, or `null` if uncategorized. */
  category_icon: string | null;
  /** Hex color of the assigned category, or `null` if uncategorized. */
  category_color: string | null;
  /** Whether this transaction is excluded from budget/insight calculations. */
  is_excluded: boolean;
  /** User-added notes for this transaction. */
  notes: string | null;
}

/**
 * An account row enriched with computed summary data for list views.
 *
 * Combines account metadata with a live transaction count and typed fields
 * narrowed from the generated `string` types.
 */
export interface AccountWithDetails {
  /** UUID primary key of the account. */
  id: string;
  /** Name of the financial institution (e.g., "Chase", "Bank of America"). */
  institution_name: string;
  /** User-facing account name (e.g., "Checking", "Sapphire Reserve"). */
  name: string;
  /** Top-level account classification (depository or credit). */
  type: AccountType;
  /** Detailed account subtype (checking, savings, credit_card, etc.). */
  subtype: AccountSubtype;
  /** Last four digits of the account number, if available. */
  last_four: string | null;
  /** Whether the account is open or closed. */
  status: AccountStatus;
  /** Available balance as a decimal string, if provided by the institution. */
  balance_available: string | null;
  /** Ledger (posted) balance as a decimal string, if provided. */
  balance_ledger: string | null;
  /** Total number of transactions associated with this account. */
  transaction_count: number;
  /** Whether the user has hidden this account from dashboard views. */
  is_hidden: boolean;
}

/**
 * A budget enriched with current-period spend calculations for dashboard cards.
 *
 * Joins the budget definition with its current `budget_period` row and the
 * linked category's display metadata. All monetary values are pre-parsed
 * to numbers for easy rendering of progress bars and summaries.
 */
export interface BudgetWithSpend {
  /** UUID primary key of the budget. */
  id: string;
  /** Foreign key to the target spending category. */
  category_id: string;
  /** User-defined budget name. */
  name: string;
  /** Target budget amount as a decimal string. */
  amount: string;
  /** Time period over which this budget is measured. */
  period_type: BudgetPeriodType;
  /** Whether this budget is currently active. */
  is_active: boolean;
  /** Optional override color for the budget card. */
  color: string | null;
  /** Optional override icon for the budget card. */
  icon: string | null;
  /** Total amount spent in the current period (parsed to number). */
  spent: number;
  /** Budgeted amount for the current period, including any rollover (parsed to number). */
  budgeted: number;
  /** Remaining amount before hitting the budget limit (`budgeted - spent`). */
  remaining: number;
  /** Percentage of budget consumed (`spent / budgeted * 100`). */
  percentage: number;
  /** Display name of the linked category. */
  category_name: string;
  /** Display icon of the linked category. */
  category_icon: string;
}

/**
 * Net worth summary with period-over-period change calculations.
 *
 * Used by the net worth dashboard widget to show the current position
 * alongside the delta from the previous snapshot.
 */
export interface NetWorthWithChange {
  /** Current net worth (assets minus liabilities). */
  current: number;
  /** Net worth from the previous snapshot for comparison. */
  previous: number;
  /** Absolute change (`current - previous`). */
  change: number;
  /** Percentage change from previous to current. */
  changePercent: number;
  /** Total value of all asset (depository) accounts. */
  assets: number;
  /** Total value of all liability (credit) accounts. */
  liabilities: number;
}

/**
 * Aggregated financial summary for a single calendar month.
 *
 * Powers the monthly overview cards showing income, expenses, net cash flow,
 * and a ranked breakdown of top spending categories.
 */
export interface MonthlySummary {
  /** Month identifier in YYYY-MM format. */
  month: string;
  /** Total income for the month (sum of positive transaction amounts). */
  totalIncome: number;
  /** Total expenses for the month (sum of negative transaction amounts, as positive). */
  totalExpenses: number;
  /** Net cash flow for the month (`totalIncome - totalExpenses`). */
  netCashFlow: number;
  /** Top spending categories ranked by amount, with display metadata. */
  topCategories: Array<{
    /** Category display name. */
    name: string;
    /** Category emoji/icon. */
    icon: string;
    /** Category hex color. */
    color: string;
    /** Total amount spent in this category. */
    amount: number;
    /** Percentage of total monthly spending this category represents. */
    percentage: number;
  }>;
}
