/**
 * @fileoverview App type definitions for Radiant Finance.
 *
 * Entity types (database row shapes) are auto-generated by stellar-drive
 * from the schema definition in `src/lib/schema.ts`. This file re-exports
 * them and adds app-specific type narrowings that refine generated `string`
 * fields to precise union types (e.g., `AccountType = 'depository' | 'credit'`).
 */

// Re-export stellar-drive utility types
export type { SyncStatus, AuthMode, OfflineCredentials } from 'stellar-drive/types';

// Re-export all generated entity types
export type {
  TellerEnrollment,
  Account,
  Transaction,
  Category,
  RecurringTransaction
} from './types.generated';

/* ═══════════════════════════════════════════════════════════════════════════
   TYPE NARROWINGS — Refine generated `string` types to precise unions
   ═══════════════════════════════════════════════════════════════════════════ */

/**
 * Top-level account classification from the Teller API.
 *
 * - `'depository'` — Bank accounts (checking, savings, money market, etc.)
 * - `'credit'` — Credit card accounts
 */
export type AccountType = 'depository' | 'credit';

/**
 * How the account was connected.
 *
 * - `'teller'` — Linked via Teller Connect (automated sync)
 * - `'manual'` — Created manually (CSV import for transactions)
 */
export type AccountSource = 'teller' | 'manual';

/**
 * Detailed account subtype from the Teller API.
 *
 * Depository subtypes: checking, savings, money_market, certificate_of_deposit, treasury, sweep.
 * Credit subtypes: credit_card.
 */
export type AccountSubtype =
  | 'checking'
  | 'savings'
  | 'money_market'
  | 'certificate_of_deposit'
  | 'treasury'
  | 'sweep'
  | 'credit_card';

/**
 * Whether a financial account is currently active or has been closed.
 */
export type AccountStatus = 'open' | 'closed';

/**
 * Settlement status of a transaction from the Teller API.
 */
export type TransactionStatus = 'posted' | 'pending';

/**
 * How often a recurring transaction repeats.
 */
export type RecurringFrequency = 'weekly' | 'biweekly' | 'monthly' | 'yearly';

/**
 * How a recurring transaction entry was created.
 */
export type RecurringSource = 'manual' | 'auto-detected';

/**
 * Lifecycle state of a recurring transaction.
 */
export type RecurringStatus = 'active' | 'paused' | 'ended';

/**
 * Connection health of a Teller enrollment.
 */
export type EnrollmentStatus = 'connected' | 'disconnected' | 'error';

/**
 * Teller API environment selector.
 */
export type TellerEnvironment = 'sandbox' | 'development' | 'production';

/* ═══════════════════════════════════════════════════════════════════════════
   COMPOSITE TYPES — Rich types with joined/computed data
   ═══════════════════════════════════════════════════════════════════════════ */

/**
 * A transaction row enriched with its resolved category display metadata.
 */
export interface TransactionWithCategory {
  id: string;
  account_id: string;
  amount: string;
  date: string;
  description: string;
  counterparty_name: string | null;
  status: TransactionStatus;
  type: string | null;
  category_name: string | null;
  category_icon: string | null;
  category_color: string | null;
  is_excluded: boolean;
  notes: string | null;
}

/**
 * An account row enriched with computed summary data for list views.
 */
export interface AccountWithDetails {
  id: string;
  institution_name: string;
  name: string;
  type: AccountType;
  subtype: AccountSubtype;
  last_four: string | null;
  status: AccountStatus;
  balance_available: string | null;
  balance_ledger: string | null;
  transaction_count: number;
  is_hidden: boolean;
}
